---
- name: Ruter1 config
  hosts: R1
  gather_facts: false
  connection: network_cli
  tasks:
    - name: gig0/0/1
      ios_config:
        parents: interface Gig0/0/1
        lines:
          - no shutdown
    - name: SUBINT 20 STUD2 VLAN
      ios_config:
        parents: interface gig0/0/1.20
        lines:
          - encapsulation dot1Q 20
          - ip address 10.10.20.2 255.255.255.0
          - no shutdown
    - name: SUBINT 99 MGMT
      ios_config:
        parents: interface gig0/0/1.99
        lines:
          - encapsulation dot1Q 99
          - ip address 10.10.99.12 255.255.255.0
          - no shutdown
    - name: HSRP opp til mgmt
      ios_config:
        parents: interface gig0/0/0
        lines:
          - standby 1 ip 172.16.0.1
          - standby 1 priority 110
          - standby 1 preempt
    - name: HSRP Til 20
      ios_config:
        parents: interface gig0/0/1.20
        lines:
          - standby 2 ip 10.10.20.1
          - standby 2 priority 110
          - standby 2 preempt
    - name: HSRP til 99
      ios_config:
        parents: interface gig0/0/1.99
        lines:
          - standby 3 ip 10.10.99.11
          - standby 3 priority 110
          - standby 3 preempt

    - name: DHCP
      ios_config:
        parents: ip dhcp pool STUD2
        lines:
          - network 10.10.20.0 255.255.255.0
          - default-router 10.10.20.1
    - name: EXCLUDE
      ios_config:
        lines:
          - ip dhcp excluded-address 10.10.20.1 10.10.20.99
          - ip dhcp excluded-address 10.10.20.150 10.10.20.255
